// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flkhxbxnhbfklmdjtnqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsa2h4YnhuaGJma2xtZGp0bnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODU4OTYsImV4cCI6MjA2NzU2MTg5Nn0.YqxUuORutvDIYsLvloz2EKCeIdRntx8tB8J76Pqgf5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});